"""add_is_approved_to_user_model

Revision ID: 23e863c7ef3b
Revises: 179b8025fb43
Create Date: 2025-10-27 12:52:29.691033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23e863c7ef3b"
down_revision: Union[str, Sequence[str], None] = "179b8025fb43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_approved", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_approved")
    # ### end Alembic commands ###
