"""change_is_liscensed_to_is_licensed_in_facilities

Revision ID: 661f8ea08698
Revises: c64f41994df4
Create Date: 2026-04-13 16:56:24.252375

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "661f8ea08698"
down_revision: Union[str, Sequence[str], None] = "c64f41994df4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("facilities", sa.Column("is_licensed", sa.Boolean(), nullable=True))
    op.drop_column("facilities", "is_liscensed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facilities", sa.Column("is_liscensed", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True)
    )
    op.drop_column("facilities", "is_licensed")
    # ### end Alembic commands ###
